// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/browser/data/models/bookmark.dart';
import 'features/browser/data/models/browser_history.dart';
import 'features/browser/data/models/tab_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7019150322048980087),
    name: 'BrowserHistory',
    lastPropertyId: const obx_int.IdUid(4, 8556009526199344133),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4285568193290614294),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7710223420981656087),
        name: 'url',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8775823442219128105),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8556009526199344133),
        name: 'timestamp',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 6376501229577372533),
    name: 'Bookmark',
    lastPropertyId: const obx_int.IdUid(7, 1832949028764956111),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5451333729995137117),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3396357631752573292),
        name: 'url',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1154822111520146154),
        name: 'iconUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2923236057249595842),
        name: 'timestamp',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 879063838743391201),
        name: 'typeString',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3347061827680879486),
        name: 'score',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1832949028764956111),
        name: 'title',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 1923416986273577909),
    name: 'TabEntity',
    lastPropertyId: const obx_int.IdUid(6, 5339588714681877315),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6703680030027071551),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5141464918355808934),
        name: 'tabId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4897258136141295674),
        name: 'tabIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7181473789280925111),
        name: 'url',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3414454135073186159),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5339588714681877315),
        name: 'isActive',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 1923416986273577909),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    BrowserHistory: obx_int.EntityDefinition<BrowserHistory>(
      model: _entities[0],
      toOneRelations: (BrowserHistory object) => [],
      toManyRelations: (BrowserHistory object) => {},
      getId: (BrowserHistory object) => object.id,
      setId: (BrowserHistory object, int id) {
        object.id = id;
      },
      objectToFB: (BrowserHistory object, fb.Builder fbb) {
        final urlOffset = fbb.writeString(object.url);
        final titleOffset = fbb.writeString(object.title);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, urlOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addInt64(3, object.timestamp);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final urlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final timestampParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = BrowserHistory(
          id: idParam,
          url: urlParam,
          title: titleParam,
          timestamp: timestampParam,
        );

        return object;
      },
    ),
    Bookmark: obx_int.EntityDefinition<Bookmark>(
      model: _entities[1],
      toOneRelations: (Bookmark object) => [],
      toManyRelations: (Bookmark object) => {},
      getId: (Bookmark object) => object.id,
      setId: (Bookmark object, int id) {
        object.id = id;
      },
      objectToFB: (Bookmark object, fb.Builder fbb) {
        final urlOffset = fbb.writeString(object.url);
        final iconUrlOffset = object.iconUrl == null
            ? null
            : fbb.writeString(object.iconUrl!);
        final typeStringOffset = fbb.writeString(object.typeString);
        final titleOffset = object.title == null
            ? null
            : fbb.writeString(object.title!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, urlOffset);
        fbb.addOffset(2, iconUrlOffset);
        fbb.addInt64(3, object.timestamp);
        fbb.addOffset(4, typeStringOffset);
        fbb.addFloat64(5, object.score);
        fbb.addOffset(6, titleOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final urlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final iconUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final timestampParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final typeStringParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final scoreParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = Bookmark(
          id: idParam,
          url: urlParam,
          title: titleParam,
          iconUrl: iconUrlParam,
          timestamp: timestampParam,
          typeString: typeStringParam,
          score: scoreParam,
        );

        return object;
      },
    ),
    TabEntity: obx_int.EntityDefinition<TabEntity>(
      model: _entities[2],
      toOneRelations: (TabEntity object) => [],
      toManyRelations: (TabEntity object) => {},
      getId: (TabEntity object) => object.id,
      setId: (TabEntity object, int id) {
        object.id = id;
      },
      objectToFB: (TabEntity object, fb.Builder fbb) {
        final tabIdOffset = fbb.writeString(object.tabId);
        final urlOffset = fbb.writeString(object.url);
        final titleOffset = fbb.writeString(object.title);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, tabIdOffset);
        fbb.addInt64(2, object.tabIndex);
        fbb.addOffset(3, urlOffset);
        fbb.addOffset(4, titleOffset);
        fbb.addBool(5, object.isActive);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final tabIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final tabIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final urlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final isActiveParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final object = TabEntity(
          id: idParam,
          tabId: tabIdParam,
          tabIndex: tabIndexParam,
          url: urlParam,
          title: titleParam,
          isActive: isActiveParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [BrowserHistory] entity fields to define ObjectBox queries.
class BrowserHistory_ {
  /// See [BrowserHistory.id].
  static final id = obx.QueryIntegerProperty<BrowserHistory>(
    _entities[0].properties[0],
  );

  /// See [BrowserHistory.url].
  static final url = obx.QueryStringProperty<BrowserHistory>(
    _entities[0].properties[1],
  );

  /// See [BrowserHistory.title].
  static final title = obx.QueryStringProperty<BrowserHistory>(
    _entities[0].properties[2],
  );

  /// See [BrowserHistory.timestamp].
  static final timestamp = obx.QueryIntegerProperty<BrowserHistory>(
    _entities[0].properties[3],
  );
}

/// [Bookmark] entity fields to define ObjectBox queries.
class Bookmark_ {
  /// See [Bookmark.id].
  static final id = obx.QueryIntegerProperty<Bookmark>(
    _entities[1].properties[0],
  );

  /// See [Bookmark.url].
  static final url = obx.QueryStringProperty<Bookmark>(
    _entities[1].properties[1],
  );

  /// See [Bookmark.iconUrl].
  static final iconUrl = obx.QueryStringProperty<Bookmark>(
    _entities[1].properties[2],
  );

  /// See [Bookmark.timestamp].
  static final timestamp = obx.QueryIntegerProperty<Bookmark>(
    _entities[1].properties[3],
  );

  /// See [Bookmark.typeString].
  static final typeString = obx.QueryStringProperty<Bookmark>(
    _entities[1].properties[4],
  );

  /// See [Bookmark.score].
  static final score = obx.QueryDoubleProperty<Bookmark>(
    _entities[1].properties[5],
  );

  /// See [Bookmark.title].
  static final title = obx.QueryStringProperty<Bookmark>(
    _entities[1].properties[6],
  );
}

/// [TabEntity] entity fields to define ObjectBox queries.
class TabEntity_ {
  /// See [TabEntity.id].
  static final id = obx.QueryIntegerProperty<TabEntity>(
    _entities[2].properties[0],
  );

  /// See [TabEntity.tabId].
  static final tabId = obx.QueryStringProperty<TabEntity>(
    _entities[2].properties[1],
  );

  /// See [TabEntity.tabIndex].
  static final tabIndex = obx.QueryIntegerProperty<TabEntity>(
    _entities[2].properties[2],
  );

  /// See [TabEntity.url].
  static final url = obx.QueryStringProperty<TabEntity>(
    _entities[2].properties[3],
  );

  /// See [TabEntity.title].
  static final title = obx.QueryStringProperty<TabEntity>(
    _entities[2].properties[4],
  );

  /// See [TabEntity.isActive].
  static final isActive = obx.QueryBooleanProperty<TabEntity>(
    _entities[2].properties[5],
  );
}
